[project]
name = "un-transcribed"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "ipykernel>=7.2.0",
    "joblib>=1.5.3",
    "jupyter>=1.1.1",
    "pandas>=3.0.0",
    "tiktoken>=0.12.0",
]
